-- 受众面进订阅规则（issue #84）
-- audiences_json：订阅者勾选的受众面（'public' 公众广域 / 'sector' 行业专业），JSON 数组存 TEXT。
--   它是**收窄条件**，与关键词 / 领域 / 机关是 AND：那三项答"这条跟我有没有关系"，
--   受众面答"这类公示是不是给我看的"。
-- 为什么要一列而不是塞进 pending_rules_json：正式规则必须是可查的列 ——
--   后台、审计脚本与"这一行现在到底订了什么"都要读得到（同 0014 把待确认改动
--   单独放一列的理由，只是方向相反：那份是暂存，这份是生效值）。
-- **默认 '[]' 即"不限"**：存量订阅因此与旧版行为逐条一致，不需要任何回填
--   （NOT NULL + DEFAULT 让存量行直接拿到空数组，而不是 NULL —— NULL 会让
--   读侧多一条"到底是没设还是解析失败"的歧义）。
ALTER TABLE `subscriptions` ADD `audiences_json` text NOT NULL DEFAULT '[]';
